version: '3'

services:
  cnc_database:
    container_name: cnc_database

    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  cnc-web:
    container_name: cnc-web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./apps/web:/app
