version: '3'

services:
  cnc_database:
    container_name: cnc_database

    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  cnc-react:
    container_name: cnc_react
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./apps/frontend:/app
