services:
  cnc_database:
    container_name: cnc_database
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - cnc_dashboard

  cnc_frontend:
    container_name: cnc_frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - '5174:5173'
    networks:
      - cnc_dashboard

networks:
  cnc_dashboard:
